#!/usr/bin/env node
import { spawn } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import url from "node:url";

import { startMockBackend, type MockBackend } from "../mock-backend/server.js";
import { seedFreshHome, type SeededHome } from "./seed-credentials.js";
import { startCopillmAgainstMock, type CopillmDaemon } from "./spawn-copillm.js";
import { buildWindowsCmdInvocation } from "../../src/cli/windowsSpawn.js";

interface AssertionFailure {
  scenario: string;
  detail: string;
}

interface CommandResult {
  stdout: string;
  stderr: string;
  exitCode: number | null;
  signal: NodeJS.Signals | null;
}

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const CLI_ENTRY = path.join(REPO_ROOT, "dist", "cli.js");

const CODEX_PACKAGE = process.env.COPILLM_E2E_CODEX_PACKAGE ?? "@openai/codex@latest";
const CLAUDE_PACKAGE = process.env.COPILLM_E2E_CLAUDE_PACKAGE ?? "@anthropic-ai/claude-code@latest";

async function main(): Promise<void> {
  const failures: AssertionFailure[] = [];
  let mock: MockBackend | null = null;
  let seeded: SeededHome | null = null;
  let daemon: CopillmDaemon | null = null;
  try {
    mock = await startMockBackend();
    log(`mock backend listening on ${mock.baseUrl}`);

    seeded = seedFreshHome();
    log(`seeded copillm home at ${seeded.copillmHome}`);

    daemon = await startCopillmAgainstMock({
      copillmHome: seeded.copillmHome,
      upstreamBaseUrl: mock.baseUrl,
      tokenExchangeUrl: mock.tokenExchangeUrl,
      githubUserUrl: mock.githubUserUrl,
      cliEntry: CLI_ENTRY
    });
    log(`copillm daemon up at ${daemon.baseUrl} (pid ${daemon.pid})`);

    await runScenario(failures, "real-codex-cli", async () => {
      const codexHome = await prepareCodexHome(seeded!.copillmHome, daemon!.baseUrl);
      // Install into an isolated prefix and locate either the traditional npm
      // shim or the native vendor binary used by current Codex releases.
      const result = await runCodexCli(
        CODEX_PACKAGE,
        ["exec", "--skip-git-repo-check", "--model", "gpt-test-codex", "-"],
        {
          env: { ...process.env, CODEX_HOME: codexHome },
          timeoutMs: 180_000,
          stdin: "Reply with the literal string ok-from-mock and nothing else.\n"
        }
      );
      assertExitZero(result, "Real Codex CLI invocation");
      assertContainsText(result.stdout, "ok-from-mock", "Real Codex CLI output should contain mock reply");
    });

    await runScenario(failures, "real-claude-code-cli", async () => {
      const env: NodeJS.ProcessEnv = {
        ...process.env,
        ANTHROPIC_BASE_URL: `${daemon!.baseUrl}/anthropic`,
        ANTHROPIC_AUTH_TOKEN: "copillm-local-test",
        ANTHROPIC_DEFAULT_OPUS_MODEL: "claude-test-opus",
        ANTHROPIC_DEFAULT_SONNET_MODEL: "claude-test-sonnet",
        ANTHROPIC_DEFAULT_HAIKU_MODEL: "claude-test-haiku",
        CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY: "1",
        CLAUDE_CODE_SIMPLE: "1"
      };
      const result = await runCommand(
        ["npx", "-y", CLAUDE_PACKAGE, "--bare", "--print", "--allow-dangerously-skip-permissions", "--model", "claude-test-sonnet", "Reply with the literal string ok-from-mock and nothing else."],
        { env, timeoutMs: 180_000 }
      );
      assertExitZero(result, "Real Claude Code CLI invocation");
      assertContainsText(result.stdout, "ok-from-mock", "Real Claude Code CLI output should contain mock reply");
    });
  } catch (error) {
    failures.push({
      scenario: "fixture-setup",
      detail: error instanceof Error ? error.stack ?? error.message : String(error)
    });
  } finally {
    if (daemon) await daemon.stop();
    if (mock) await mock.close();
    if (seeded) seeded.cleanup();
  }

  if (failures.length > 0) {
    process.stderr.write(`\n\u2717 release-gate runner: ${failures.length} failure(s)\n\n`);
    for (const f of failures) {
      process.stderr.write(`  [${f.scenario}] ${f.detail}\n\n`);
    }
    process.exit(1);
  }
  process.stdout.write(`\n\u2713 release-gate runner: all scenarios passed\n`);
}

async function prepareCodexHome(copillmHome: string, copillmBaseUrl: string): Promise<string> {
  const codexHome = path.join(copillmHome, "codex");
  fs.mkdirSync(codexHome, { recursive: true });
  const toml = [
    `# Generated by release-runner.ts`,
    `model = "gpt-test-codex"`,
    `model_provider = "copillm"`,
    `model_reasoning_effort = "medium"`,
    `approvals_reviewer = "user"`,
    ``,
    `[model_providers.copillm]`,
    `name = "copillm"`,
    `base_url = "${copillmBaseUrl}/codex/v1"`,
    `wire_api = "responses"`,
    `requires_openai_auth = false`,
    ``
  ].join("\n");
  fs.writeFileSync(path.join(codexHome, "config.toml"), toml, { mode: 0o600 });
  return codexHome;
}

async function runCodexCli(
  packageSpec: string,
  args: string[],
  options: { env?: NodeJS.ProcessEnv; timeoutMs?: number; stdin?: string }
): Promise<CommandResult> {
  const installRoot = fs.mkdtempSync(path.join(os.tmpdir(), "copillm-codex-e2e-"));
  try {
    const installSpec = await codexInstallSpec(packageSpec, options);
    const install = await runCommand(
      [
        "npm",
        "install",
        "--prefix",
        installRoot,
        "--no-audit",
        "--no-fund",
        "--omit=dev",
        "--include=optional",
        "--ignore-scripts",
        installSpec
      ],
      { env: options.env, timeoutMs: options.timeoutMs }
    );
    assertExitZero(install, `Codex package install (${installSpec})`);
    const executable = findCodexExecutable(installRoot);
    if (!executable) {
      throw new Error(`Installed ${packageSpec} did not expose a codex executable.`);
    }
    return await runCommand([executable, ...args], options);
  } finally {
    // Native Codex can release Windows file handles shortly after process close.
    fs.rmSync(installRoot, {
      recursive: true,
      force: true,
      ...(process.platform === "win32" ? { maxRetries: 20, retryDelay: 250 } : {})
    });
  }
}

async function codexInstallSpec(
  packageSpec: string,
  options: { env?: NodeJS.ProcessEnv; timeoutMs?: number }
): Promise<string> {
  if (packageSpec !== "@openai/codex@latest") return packageSpec;
  const view = await runCommand(
    ["npm", "view", packageSpec, "version"],
    { env: options.env, timeoutMs: options.timeoutMs }
  );
  assertExitZero(view, `Codex package metadata lookup (${packageSpec})`);
  const version = view.stdout.trim();
  const match = version.match(/^(.*)-(linux|darwin|win32)-(x64|arm64)(-musl)?$/);
  if (!match) return packageSpec;
  const currentPlatform = `${process.platform}-${process.arch}`;
  const discoveredPlatform = `${match[2]}-${match[3]}${match[4] ?? ""}`;
  return discoveredPlatform === currentPlatform ? packageSpec : `@openai/codex@${match[1]}`;
}

function findCodexExecutable(prefix: string): null | string {
  const shimName = process.platform === "win32" ? "codex.cmd" : "codex";
  const shimPath = path.join(prefix, "node_modules", ".bin", shimName);
  if (fs.existsSync(shimPath)) return shimPath;

  const vendorDir = path.join(prefix, "node_modules", "@openai", "codex", "vendor");
  if (!fs.existsSync(vendorDir)) return null;
  const binaryName = process.platform === "win32" ? "codex.exe" : "codex";
  const pending = [vendorDir];
  while (pending.length > 0) {
    const currentDir = pending.pop()!;
    for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
      const entryPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        pending.push(entryPath);
      } else if (entry.name === binaryName) {
        return entryPath;
      }
    }
  }
  return null;
}

async function runCommand(
  command: readonly string[],
  options: { env?: NodeJS.ProcessEnv; timeoutMs?: number; stdin?: string } = {}
): Promise<CommandResult> {
  return new Promise((resolve, reject) => {
    const [exe, ...args] = command;
    const stdinMode = options.stdin !== undefined ? "pipe" : "ignore";
    const windowsInvocation = process.platform === "win32"
      ? buildWindowsCmdInvocation(exe === "npx" ? "npx.cmd" : exe, args)
      : null;
    const child = spawn(
      windowsInvocation?.command ?? exe,
      windowsInvocation?.args ?? args,
      {
        env: options.env ?? process.env,
        stdio: [stdinMode, "pipe", "pipe"],
        shell: false,
        ...(windowsInvocation ? { windowsVerbatimArguments: true } : {})
      }
    );
    if (options.stdin !== undefined) {
      child.stdin?.end(options.stdin);
    }
    let stdout = "";
    let stderr = "";
    child.stdout?.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString("utf8");
    });
    const timer = options.timeoutMs
      ? setTimeout(() => {
          child.kill("SIGKILL");
          reject(new Error(`Command timed out after ${options.timeoutMs}ms: ${command.join(" ")}\nstdout:\n${stdout}\nstderr:\n${stderr}`));
        }, options.timeoutMs)
      : null;
    child.on("error", (err) => {
      if (timer) clearTimeout(timer);
      reject(err);
    });
    child.on("close", (code, signal) => {
      if (timer) clearTimeout(timer);
      resolve({ stdout, stderr, exitCode: code, signal });
    });
  });
}

async function runScenario(failures: AssertionFailure[], name: string, fn: () => Promise<void>): Promise<void> {
  process.stdout.write(`  > ${name}... `);
  try {
    await fn();
    process.stdout.write("ok\n");
  } catch (error) {
    process.stdout.write("FAIL\n");
    failures.push({ scenario: name, detail: error instanceof Error ? error.message : String(error) });
  }
}

function assertExitZero(result: CommandResult, label: string): void {
  if (result.exitCode !== 0) {
    throw new Error(
      `${label} exit code ${result.exitCode} (signal=${result.signal ?? "none"})\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`
    );
  }
}

function assertContainsText(haystack: string, needle: string, msg: string): void {
  if (!haystack.includes(needle)) {
    throw new Error(`${msg}\nexpected substring: ${needle}\ngot:\n${haystack}`);
  }
}

function log(line: string): void {
  process.stdout.write(`[release-gate] ${line}\n`);
}

main().catch((error) => {
  process.stderr.write(`release-gate runner crashed: ${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
  process.exit(1);
});
