import fs from "node:fs";
import path from "node:path";
import { CopilotTokenManager } from "../../auth/copilotToken.js";
import { loadStoredCredential } from "../../auth/credentials.js";
import { loadConfig } from "../../config/config.js";
import { listModelsUnion } from "../../models/discovery.js";
import { ensureSecureDirectory, writeFileSecureAtomic } from "../../config/fsSecurity.js";
import { buildCodexCatalog } from "../../server/codexSchema.js";
import { inspectLock } from "../../server/lock.js";

export interface CodexInitOptions {
  outDir: string;
  model: string | null;
  port: number;
  providerId: string;
  reasoningEffort: string | null;
}

export interface CodexInitResult {
  outDir: string;
  configPath: string;
  modelCount: number;
  defaultModel: string;
  proxyUrl: string;
  exportCommand: string;
}

export async function generateCodexHome(options: CodexInitOptions): Promise<CodexInitResult> {
  const config = loadConfig();
  const creds = await loadStoredCredential();
  if (!creds) {
    throw new Error("Not authenticated. Run `copillm login` first.");
  }

  const tokenManager = new CopilotTokenManager(creds.token);
  await tokenManager.ensureToken(false);
  const discovery = await listModelsUnion(config.accountType, creds.token, 3);
  const catalog = buildCodexCatalog(discovery.models);
  if (catalog.models.length === 0) {
    throw new Error("No Codex-eligible models found in the live catalog.");
  }

  const port = options.port;
  const proxyUrl = `http://127.0.0.1:${port}/codex/v1`;
  const baseUrl = proxyUrl;
  const defaultModel = options.model ?? pickDefaultModel(catalog.models.map((model) => model.slug));
  if (!catalog.models.some((model) => model.slug === defaultModel)) {
    throw new Error(
      `Requested model "${defaultModel}" is not in the eligible catalog. Available: ${catalog.models.map((model) => model.slug).join(", ")}`
    );
  }

  const absOutDir = path.resolve(options.outDir);
  ensureSecureDirectory(absOutDir);

  const configPath = path.join(absOutDir, "config.toml");
  const reasoningEffort = options.reasoningEffort ?? "medium";
  const tomlBody = renderConfigToml({
    model: defaultModel,
    reasoningEffort,
    providerId: options.providerId,
    baseUrl
  });
  writeFileSecureAtomic(configPath, tomlBody, 0o600);

  return {
    outDir: absOutDir,
    configPath,
    modelCount: catalog.models.length,
    defaultModel,
    proxyUrl,
    exportCommand: `CODEX_HOME=${absOutDir} codex`
  };
}

function pickDefaultModel(slugs: readonly string[]): string {
  const preferred = ["gpt-5.3-codex", "gpt-5.2-codex", "gpt-5.4", "gpt-5.2", "claude-opus-4.5", "claude-sonnet-4.6"];
  for (const candidate of preferred) {
    if (slugs.includes(candidate)) {
      return candidate;
    }
  }
  return slugs[0];
}

function renderConfigToml(input: {
  model: string;
  reasoningEffort: string;
  providerId: string;
  baseUrl: string;
}): string {
  return [
    `# Generated by \`copillm start\` on ${new Date().toISOString()}`,
    `# Use with: CODEX_HOME=<this directory> codex`,
    ``,
    `model = "${input.model}"`,
    `model_provider = "${input.providerId}"`,
    `model_reasoning_effort = "${input.reasoningEffort}"`,
    `approvals_reviewer = "user"`,
    ``,
    `[model_providers.${input.providerId}]`,
    `name = "copillm"`,
    `base_url = "${input.baseUrl}"`,
    `wire_api = "responses"`,
    `requires_openai_auth = false`,
    ``
  ].join("\n");
}

export function defaultOutputDir(home: string): string {
  return path.join(home, "codex");
}

export function listExistingCodexHomes(home: string): string[] {
  const dir = path.join(home, "codex");
  if (!fs.existsSync(dir)) {
    return [];
  }
  return [dir];
}

export function proxyPortFromLock(): number | null {
  const inspection = inspectLock();
  if (inspection.state === "running") {
    return inspection.lock.port;
  }
  return null;
}
