import fs from "node:fs";
import path from "node:path";
import { loadStoredCredential, type StoredCredential } from "../../auth/credentials.js";
import { loadConfig } from "../../config/config.js";
import { listModelsUnion, type ModelDiscoveryResult } from "../../models/discovery.js";
import { ensureSecureDirectory, writeFileSecureAtomic } from "../../config/fsSecurity.js";
import { buildCodexCatalog } from "../../server/codexSchema.js";
import { inspectLock } from "../../server/lock.js";
import type { AppConfig } from "../../types/index.js";

export interface CodexInitOptions {
  outDir: string;
  model: string | null;
  port: number;
  providerId: string;
  reasoningEffort: string | null;
  /**
   * Optional pre-loaded context. When provided, `generateCodexHome` skips
   * its own `loadConfig` / `loadStoredCredential` / `listModelsUnion` calls
   * and uses the supplied values. The CLI `start` command uses this to
   * collapse 3 redundant token exchanges + 3 model-discovery calls into 1
   * across the daemon + codex + pi init steps.
   *
   * When omitted, behaviour is unchanged — `copillm codex`, `copillm env
   * codex`, and any other standalone caller continues to work as before.
   */
  precomputed?: PrecomputedStartContext;
}

/**
 * Context shared across the daemon + codex + pi steps of `copillm start`.
 *
 * Without sharing, each step independently re-runs `loadStoredCredential`
 * (a keychain read), `loadConfig` (a YAML parse), and `listModelsUnion`
 * (multiple Copilot `/models` fetches). The token exchange itself is now
 * gone from these sites (see PR 2 commit), but the remaining work is still
 * worth deduping — it cuts keychain audit-log entries and removes more
 * flake surface on the catalog fetch.
 */
export interface PrecomputedStartContext {
  creds: StoredCredential;
  config: AppConfig;
  discovery: ModelDiscoveryResult;
}

export interface CodexInitResult {
  outDir: string;
  configPath: string;
  modelCount: number;
  defaultModel: string;
  proxyUrl: string;
  exportCommand: string;
}

export async function generateCodexHome(options: CodexInitOptions): Promise<CodexInitResult> {
  const { discovery } = await resolveStartContext(options.precomputed);
  const catalog = buildCodexCatalog(discovery.models);
  if (catalog.models.length === 0) {
    throw new Error("No Codex-eligible models found in the live catalog.");
  }

  const port = options.port;
  const proxyUrl = `http://127.0.0.1:${port}/codex/v1`;
  const baseUrl = proxyUrl;
  const defaultModel = options.model ?? pickDefaultModel(catalog.models.map((model) => model.slug));
  if (!catalog.models.some((model) => model.slug === defaultModel)) {
    throw new Error(
      `Requested model "${defaultModel}" is not in the eligible catalog. Available: ${catalog.models.map((model) => model.slug).join(", ")}`
    );
  }

  const absOutDir = path.resolve(options.outDir);
  ensureSecureDirectory(absOutDir);

  const configPath = path.join(absOutDir, "config.toml");
  const reasoningEffort = options.reasoningEffort ?? "medium";
  const tomlBody = renderConfigToml({
    model: defaultModel,
    reasoningEffort,
    providerId: options.providerId,
    baseUrl
  });
  writeFileSecureAtomic(configPath, tomlBody, 0o600);

  return {
    outDir: absOutDir,
    configPath,
    modelCount: catalog.models.length,
    defaultModel,
    proxyUrl,
    exportCommand: `CODEX_HOME=${absOutDir} codex`
  };
}

/**
 * Load credentials / config / model discovery once. When the caller has
 * already done this work (e.g. `copillm start` orchestrating multiple init
 * steps), it can pass them in via `precomputed` to skip the work.
 *
 * Exported so `generatePiHome` (and any future agent init) can use the
 * same loader and the same "if precomputed, reuse it" contract.
 */
export async function resolveStartContext(precomputed?: PrecomputedStartContext): Promise<PrecomputedStartContext> {
  if (precomputed) {
    return precomputed;
  }
  const config = loadConfig();
  const creds = await loadStoredCredential();
  if (!creds) {
    throw new Error("Not authenticated. Run `copillm login` first.");
  }
  const discovery = await listModelsUnion(config.accountType, creds.token, 3);
  return { config, creds, discovery };
}

function pickDefaultModel(slugs: readonly string[]): string {
  const preferred = ["gpt-5.3-codex", "gpt-5.2-codex", "gpt-5.4", "gpt-5.2", "claude-opus-4.5", "claude-sonnet-4.6"];
  for (const candidate of preferred) {
    if (slugs.includes(candidate)) {
      return candidate;
    }
  }
  return slugs[0];
}

function renderConfigToml(input: {
  model: string;
  reasoningEffort: string;
  providerId: string;
  baseUrl: string;
}): string {
  return [
    `# Generated by \`copillm start\` on ${new Date().toISOString()}`,
    `# Use with: CODEX_HOME=<this directory> codex`,
    ``,
    `model = "${input.model}"`,
    `model_provider = "${input.providerId}"`,
    `model_reasoning_effort = "${input.reasoningEffort}"`,
    `approvals_reviewer = "user"`,
    ``,
    `[model_providers.${input.providerId}]`,
    `name = "copillm"`,
    `base_url = "${input.baseUrl}"`,
    `wire_api = "responses"`,
    `requires_openai_auth = false`,
    ``
  ].join("\n");
}

export function defaultOutputDir(home: string): string {
  return path.join(home, "codex");
}

export function listExistingCodexHomes(home: string): string[] {
  const dir = path.join(home, "codex");
  if (!fs.existsSync(dir)) {
    return [];
  }
  return [dir];
}

export function proxyPortFromLock(): number | null {
  const inspection = inspectLock();
  if (inspection.state === "running") {
    return inspection.lock.port;
  }
  return null;
}
