#!/usr/bin/env node
// Installs a global `copillm-dev` command that runs THIS checkout's build in
// isolated --dev mode (COPILLM_HOME=~/.copillm-dev, dev port 4142).
//
// Why not `npm link`? `npm link` is tied to the package's published bin name
// (`copillm`), so it would overwrite your production `copillm`. Adding a second
// `copillm-dev` bin to package.json would instead ship that command to every
// end user. This script sidesteps both: it writes a small wrapper shim only on
// the developer's machine, never touches the production `copillm`, and changes
// nothing in the published package (the `bin` field stays `copillm`-only, and
// `scripts/` is excluded from `files`).
//
// Usage: `npm run dev:link`  (undo with `npm run dev:unlink`).
import { execSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const NAME = "copillm-dev";
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cliJs = join(repoRoot, "dist", "cli.js");
const binDir = globalBinDir();

mkdirSync(binDir, { recursive: true });

if (process.platform === "win32") {
  const banner = `${NAME} - dev build in isolated --dev mode. Generated by npm run dev:link.`;
  writeFileSync(join(binDir, `${NAME}.cmd`), `@ECHO OFF\r\nREM ${banner}\r\nnode "${cliJs}" --dev %*\r\n`);
  writeFileSync(join(binDir, `${NAME}.ps1`), `# ${banner}\n& node "${cliJs}" --dev @args\nexit $LASTEXITCODE\n`);
  // Bash shim (Git Bash) — node accepts forward slashes on Windows.
  writeFileSync(join(binDir, NAME), `#!/bin/sh\n# ${banner}\nexec node "${cliJs.replace(/\\/g, "/")}" --dev "$@"\n`);
} else {
  const shim = join(binDir, NAME);
  writeFileSync(shim, `#!/bin/sh\n# ${NAME} - dev build in isolated --dev mode. Generated by npm run dev:link.\nexec node "${cliJs}" --dev "$@"\n`);
  chmodSync(shim, 0o755);
}

console.log(`Linked \`${NAME}\` -> node "${cliJs}" --dev   (in ${binDir})`);
if (!existsSync(cliJs)) {
  console.log(`NOTE: ${cliJs} does not exist yet — run \`npm run build\` before using \`${NAME}\`.`);
}
console.log(`Try:  ${NAME} start --detach   then   ${NAME} claude        (undo: npm run dev:unlink)`);

function globalBinDir() {
  // On Windows global bins live directly in the npm prefix; on POSIX in <prefix>/bin.
  const prefix = execSync("npm prefix -g", { encoding: "utf8" }).trim();
  return process.platform === "win32" ? prefix : join(prefix, "bin");
}
